// Generated by CoffeeScript 1.6.3
(function() {
  var idx, method, methods, _fn, _i, _len;

  window.logging || (window.logging = {});

  window.logging.level || (window.logging.level = 1);

  methods = ["debug", "warn", "info", "log", "error"];

  _fn = function(method, idx) {
    return logging[method] = function() {
      var console;
      console = window.console;
      if (!console || !console[method]) {
        return;
      }
      if (idx < logging.level) {
        return;
      }
      return console[method].apply(console, arguments);
    };
  };
  for (idx = _i = 0, _len = methods.length; _i < _len; idx = ++_i) {
    method = methods[idx];
    _fn(method, idx);
  }

}).call(this);
